import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Briefcase, Bot, FileText, LayoutDashboard, Plus, Search, ShieldCheck, Sparkles, Upload, Download, CheckCircle2 } from 'lucide-react';
import './styles.css';

const api = async (path, options = {}) => {
  const res = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  if (!res.ok) throw new Error(await res.text());
  return res.status === 204 ? null : res.json();
};
const money = (n) => new Intl.NumberFormat('en-US').format(n || 0);

function App() {
  const [state, setState] = useState(null); const [tab, setTab] = useState('overview'); const [err, setErr] = useState('');
  const load = () => api('/api/state').then(setState).catch((e) => setErr(e.message));
  useEffect(load, []);
  const tabs = [ ['overview', LayoutDashboard], ['tracker', Briefcase], ['board', Search], ['resume', FileText], ['agent', Bot], ['privacy', ShieldCheck] ];
  if (!state) return <div className="splash"><Sparkles /> Loading local JobHuntr…</div>;
  return <div className="app">
    <aside><div className="brand"><div className="logo">JH</div><div><b>JobHuntr OSS</b><span>Local-first job search</span></div></div>{tabs.map(([name, Icon]) => <button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={18}/>{name}</button>)}<p className="local">No cloud. No accounts. Data stays in <code>./data</code>.</p></aside>
    <main><header><div><h1>{title(tab)}</h1><p>{subtitle(tab)}</p></div><button onClick={load}>Refresh</button></header>{err && <div className="error">{err}</div>}
      {tab==='overview' && <Overview state={state} setTab={setTab}/>} {tab==='tracker' && <Tracker state={state} reload={load}/>} {tab==='board' && <Board reload={load}/>} {tab==='resume' && <Resume state={state} reload={load}/>} {tab==='agent' && <Agent state={state} reload={load}/>} {tab==='privacy' && <Privacy />}
    </main>
  </div>;
}
function title(t){return {overview:'Command center',tracker:'Application tracker',board:'Local job board',resume:'Resume & cover letters',agent:'Autonomous hunt',privacy:'Privacy & safety'}[t]}
function subtitle(t){return {overview:'Your saved roles, pipeline health, tasks, and agent activity.',tracker:'Track every lead from interested to offer with notes and next steps.',board:'Search a local seed board or add roles manually; no external scraping required.',resume:'Score fit and generate editable cover-letter drafts entirely locally.',agent:'Simulate JobHuntr v2-style hunting using local rules and saved preferences.',privacy:'Built for open source: local data only and automated secret scanning.'}[t]}
function Overview({state,setTab}){ const s=state.summary; const stages=['saved','interested','applied','interview','offer','rejected']; return <section className="grid"><div className="card hero"><h2>Pipeline fit: {s.avgFit}%</h2><p>{s.totalJobs} roles tracked. {s.openTasks.length} open tasks. Data never leaves this machine.</p><button onClick={()=>setTab('agent')}><Bot size={16}/> Run local hunt</button></div><div className="card"><h3>Funnel</h3>{stages.map(st=><div className="bar" key={st}><span>{st}</span><b style={{width:`${(s.byStatus[st]||0)*18+8}%`}}>{s.byStatus[st]||0}</b></div>)}</div><div className="card"><h3>Open tasks</h3>{s.openTasks.length?s.openTasks.slice(0,8).map(t=><p className="task" key={t.id}>☐ {t.text}<small>{t.company} · {t.title}</small></p>):<p>No open tasks. Add follow-ups in Tracker.</p>}</div><div className="card wide"><h3>Activity log</h3><div className="timeline">{s.recentActivities.map(a=><p key={a.id}><time>{new Date(a.at).toLocaleString()}</time>{a.message}</p>)}</div></div></section>}
function Tracker({state,reload}){ const [form,setForm]=useState({company:'',title:'',location:'Remote',url:'',description:'',tags:''}); const [selected,setSelected]=useState(state.jobs[0]?.id); const job=state.jobs.find(j=>j.id===selected)||state.jobs[0]; const save=async()=>{await api('/api/jobs',{method:'POST',body:JSON.stringify({...form,tags:form.tags.split(',').map(s=>s.trim()).filter(Boolean)})});setForm({company:'',title:'',location:'Remote',url:'',description:'',tags:''});reload()}; const patch=async(id,body)=>{await api(`/api/jobs/${id}`,{method:'PATCH',body:JSON.stringify(body)});reload()}; return <section className="split"><div className="card"><h3>Add role</h3>{['company','title','location','url','salary','tags'].map(k=><input key={k} placeholder={k} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<textarea placeholder="job description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button onClick={save}><Plus size={16}/> Add job</button><h3>Roles</h3><div className="jobs">{state.jobs.map(j=><button key={j.id} onClick={()=>setSelected(j.id)} className={job?.id===j.id?'selected':''}><b>{j.title}</b><span>{j.company} · {j.fitScore}% · {j.status}</span></button>)}</div></div>{job&&<div className="card detail"><div className="row"><h2>{job.title}</h2><select value={job.status} onChange={e=>patch(job.id,{status:e.target.value})}>{['saved','interested','applied','interview','offer','rejected'].map(s=><option key={s}>{s}</option>)}</select></div><p className="muted">{job.company} · {job.location} · {job.salary}</p><p>{job.description}</p><div className="chips">{(job.tags||[]).map(t=><span key={t}>{t}</span>)}</div><Actions job={job} reload={reload}/></div>}</section>}
function Actions({job,reload}){ const [note,setNote]=useState(''); const [task,setTask]=useState('Follow up with recruiter'); return <><h3>Notes</h3><div className="inline"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add note"/><button onClick={async()=>{await api(`/api/jobs/${job.id}/notes`,{method:'POST',body:JSON.stringify({text:note})});setNote('');reload()}}>Save</button></div>{(job.notes||[]).map(n=><p className="note" key={n.id}>{n.text}<small>{new Date(n.at).toLocaleString()}</small></p>)}<h3>Tasks</h3><div className="inline"><input value={task} onChange={e=>setTask(e.target.value)}/><button onClick={async()=>{await api(`/api/jobs/${job.id}/tasks`,{method:'POST',body:JSON.stringify({text:task})});reload()}}>Add</button></div>{(job.tasks||[]).map(t=><label className="task" key={t.id}><input type="checkbox" checked={t.done} onChange={async e=>{await api(`/api/jobs/${job.id}/tasks/${t.id}`,{method:'PATCH',body:JSON.stringify({done:e.target.checked})});reload()}}/> {t.text}</label>)}</>}
function Board({reload}){ const [q,setQ]=useState('engineer'); const [results,setResults]=useState([]); const search=async()=>setResults(await api('/api/board/search',{method:'POST',body:JSON.stringify({q})})); useEffect(()=>{search()},[]); return <section className="card"><div className="inline"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search role, skill, company"/><button onClick={search}><Search size={16}/> Search</button></div><div className="resultgrid">{results.map((j,i)=><div className="jobcard" key={`${j.url}-${i}`}><b>{j.title}</b><span>{j.company} · {j.location}</span><p>{j.description}</p><em>{j.fitScore}% fit</em><button onClick={async()=>{await api('/api/jobs',{method:'POST',body:JSON.stringify(j)});reload()}}>Save to tracker</button></div>)}</div></section>}
function Resume({state,reload}){ const [resume,setResume]=useState(state.profile.resumeText); const [score,setScore]=useState(null); const [letter,setLetter]=useState(null); const job=state.jobs[0]; return <section className="split"><div className="card"><h3>Local profile</h3><textarea className="resume" value={resume} onChange={e=>setResume(e.target.value)}/><button onClick={async()=>{await api('/api/profile',{method:'PUT',body:JSON.stringify({resumeText:resume})});reload()}}>Save resume locally</button><button onClick={async()=>setScore(await api('/api/resume/score',{method:'POST',body:JSON.stringify({resumeText:resume,jobId:job?.id})}))}>Score vs top role</button>{score&&<div className="score"><b>{score.score}% ATS fit</b>{score.suggestions.map(s=><p key={s}>• {s}</p>)}</div>}</div><div className="card"><h3>Cover letter</h3><p>Generate an editable first draft for your newest tracked role.</p><button onClick={async()=>setLetter(await api('/api/cover-letters',{method:'POST',body:JSON.stringify({jobId:job?.id})}))}><Sparkles size={16}/> Generate draft</button><textarea className="letter" value={letter?.body||''} onChange={e=>setLetter({...letter,body:e.target.value})}/></div></section>}
function Agent({state,reload}){ const [q,setQ]=useState('product engineer'); return <section className="grid"><div className="card hero"><h2>Local autonomous hunt</h2><p>Inspired by JobHuntr v2's Infinite Hunt, this open-source version runs a deterministic local workflow: read profile → search local seed board → score fits → save matches → log actions.</p><div className="inline"><input value={q} onChange={e=>setQ(e.target.value)}/><button onClick={async()=>{await api('/api/agent-runs/start',{method:'POST',body:JSON.stringify({q,minFit:60})});reload()}}><Bot size={16}/> Start run</button></div></div><div className="card wide"><h3>Runs</h3>{state.agentRuns.map(r=><div className="run" key={r.id}><b><CheckCircle2 size={16}/> {r.status} · {r.found} matches</b>{r.actions.map(a=><p key={a}>{a}</p>)}</div>)}</div></section>}
function Privacy(){ return <section className="grid"><div className="card"><h3><ShieldCheck/> Local-first guarantees</h3><p>Backend persists JSON to <code>./data/jobhuntr.json</code>. There is no hosted database, object storage, analytics SDK, auth vendor, or payment integration.</p></div><div className="card"><h3><Upload/> Import</h3><p>Use POST <code>/api/import</code> with a prior export. Keep exports private because they may include your resume and notes.</p></div><div className="card"><h3><Download/> Export</h3><p>Download all data from <a href="/api/export">/api/export</a>. Delete <code>./data</code> to reset.</p></div><div className="card"><h3>Secret scanning</h3><p><code>npm run secret:scan</code> checks the repository for private keys, tokens, and accidentally copied env files before publishing.</p></div></section>}

createRoot(document.getElementById('root')).render(<App />);
