import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Briefcase, Bot, FileText, LayoutDashboard, Plus, Search, ShieldCheck, Sparkles, Upload, Download, CheckCircle2, Settings, Save } from 'lucide-react';
import './styles.css';

const api = async (path, options = {}) => {
  const res = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  if (!res.ok) throw new Error(await res.text());
  return res.status === 204 ? null : res.json();
};
const money = (n) => new Intl.NumberFormat('en-US').format(n || 0);

function App() {
  const [state, setState] = useState(null); const [tab, setTab] = useState('overview'); const [err, setErr] = useState('');
  const load = () => api('/api/state').then(setState).catch((e) => setErr(e.message));
  useEffect(load, []);
  const tabs = [ ['overview', LayoutDashboard], ['tracker', Briefcase], ['board', Search], ['resume', FileText], ['agent', Bot], ['settings', Settings], ['privacy', ShieldCheck] ];
  if (!state) return <div className="splash"><Sparkles /> Loading local JobHuntr…</div>;
  return <div className="app">
    <aside><div className="brand"><div className="logo">JH</div><div><b>JobHuntr OSS</b><span>Local-first job search</span></div></div>{tabs.map(([name, Icon]) => <button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={18}/>{name}</button>)}<p className="local">No cloud. No accounts. Data stays in <code>./data</code>.</p></aside>
    <main><header><div><h1>{title(tab)}</h1><p>{subtitle(tab)}</p></div><button onClick={load}>Refresh</button></header>{err && <div className="error">{err}</div>}
      {tab==='overview' && <Overview state={state} setTab={setTab}/>} {tab==='tracker' && <Tracker state={state} reload={load}/>} {tab==='board' && <Board reload={load}/>} {tab==='resume' && <Resume state={state} reload={load}/>} {tab==='agent' && <Agent state={state} reload={load}/>} {tab==='settings' && <SettingsPage state={state} reload={load}/>} {tab==='privacy' && <Privacy />}
    </main>
  </div>;
}
function title(t){return {overview:'Command center',tracker:'Application tracker',board:'Local job board',resume:'Resume studio',agent:'Autonomous hunt',settings:'Profile & preferences',privacy:'Privacy & safety'}[t]}
function subtitle(t){return {overview:'Your saved roles, pipeline health, tasks, and agent activity.',tracker:'Track every lead from interested to offer with notes and next steps.',board:'Search bundled demo roles or add listings manually.',resume:'Create versions, score ATS alignment, and draft cover letters offline.',agent:'Run a transparent local workflow using your preferences.',settings:'Control the profile and criteria used for matching.',privacy:'Back up and restore a workspace with no cloud dependency.'}[t]}
function Overview({state,setTab}){ const s=state.summary; const stages=['saved','interested','applied','interview','offer','rejected']; return <section className="grid"><div className="card hero"><h2>Pipeline fit: {s.avgFit}%</h2><p>{s.totalJobs} roles tracked. {s.openTasks.length} open tasks. Data never leaves this machine.</p><button onClick={()=>setTab('agent')}><Bot size={16}/> Run local hunt</button></div><div className="card"><h3>Funnel</h3>{stages.map(st=><div className="bar" key={st}><span>{st}</span><b style={{width:`${(s.byStatus[st]||0)*18+8}%`}}>{s.byStatus[st]||0}</b></div>)}</div><div className="card"><h3>Open tasks</h3>{s.openTasks.length?s.openTasks.slice(0,8).map(t=><p className="task" key={t.id}>☐ {t.text}<small>{t.company} · {t.title}</small></p>):<p>No open tasks. Add follow-ups in Tracker.</p>}</div><div className="card wide"><h3>Activity log</h3><div className="timeline">{s.recentActivities.map(a=><p key={a.id}><time>{new Date(a.at).toLocaleString()}</time>{a.message}</p>)}</div></div></section>}
function Tracker({state,reload}){ const [form,setForm]=useState({company:'',title:'',location:'Remote',url:'',description:'',tags:''}); const [selected,setSelected]=useState(state.jobs[0]?.id); const job=state.jobs.find(j=>j.id===selected)||state.jobs[0]; const save=async()=>{await api('/api/jobs',{method:'POST',body:JSON.stringify({...form,tags:form.tags.split(',').map(s=>s.trim()).filter(Boolean)})});setForm({company:'',title:'',location:'Remote',url:'',description:'',tags:''});reload()}; const patch=async(id,body)=>{await api(`/api/jobs/${id}`,{method:'PATCH',body:JSON.stringify(body)});reload()}; return <section className="split"><div className="card"><h3>Add role</h3>{['company','title','location','url','salary','tags'].map(k=><input key={k} placeholder={k} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<textarea placeholder="job description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button onClick={save}><Plus size={16}/> Add job</button><h3>Roles</h3><div className="jobs">{state.jobs.map(j=><button key={j.id} onClick={()=>setSelected(j.id)} className={job?.id===j.id?'selected':''}><b>{j.title}</b><span>{j.company} · {j.fitScore}% · {j.status}</span></button>)}</div></div>{job&&<div className="card detail"><div className="row"><h2>{job.title}</h2><select value={job.status} onChange={e=>patch(job.id,{status:e.target.value})}>{['saved','interested','applied','interview','offer','rejected'].map(s=><option key={s}>{s}</option>)}</select></div><p className="muted">{job.company} · {job.location} · {job.salary}</p><p>{job.description}</p><div className="chips">{(job.tags||[]).map(t=><span key={t}>{t}</span>)}</div><Actions job={job} reload={reload}/></div>}</section>}
function Actions({job,reload}){ const [note,setNote]=useState(''); const [task,setTask]=useState('Follow up with recruiter'); return <><h3>Notes</h3><div className="inline"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add note"/><button onClick={async()=>{await api(`/api/jobs/${job.id}/notes`,{method:'POST',body:JSON.stringify({text:note})});setNote('');reload()}}>Save</button></div>{(job.notes||[]).map(n=><p className="note" key={n.id}>{n.text}<small>{new Date(n.at).toLocaleString()}</small></p>)}<h3>Tasks</h3><div className="inline"><input value={task} onChange={e=>setTask(e.target.value)}/><button onClick={async()=>{await api(`/api/jobs/${job.id}/tasks`,{method:'POST',body:JSON.stringify({text:task})});reload()}}>Add</button></div>{(job.tasks||[]).map(t=><label className="task" key={t.id}><input type="checkbox" checked={t.done} onChange={async e=>{await api(`/api/jobs/${job.id}/tasks/${t.id}`,{method:'PATCH',body:JSON.stringify({done:e.target.checked})});reload()}}/> {t.text}</label>)}</>}
function Board({reload}){ const [q,setQ]=useState('engineer'); const [results,setResults]=useState([]); const search=async()=>setResults(await api('/api/board/search',{method:'POST',body:JSON.stringify({q})})); useEffect(()=>{search()},[]); return <section className="card"><div className="inline"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search role, skill, company"/><button onClick={search}><Search size={16}/> Search</button></div><div className="resultgrid">{results.map((j,i)=><div className="jobcard" key={`${j.url}-${i}`}><b>{j.title}</b><span>{j.company} · {j.location}</span><p>{j.description}</p><em>{j.fitScore}% fit</em><button onClick={async()=>{await api('/api/jobs',{method:'POST',body:JSON.stringify(j)});reload()}}>Save to tracker</button></div>)}</div></section>}
function Resume({state,reload}){ const [resume,setResume]=useState(state.profile.resumeText); const [name,setName]=useState('Targeted resume'); const [templateId,setTemplateId]=useState(state.templates?.[0]?.id||'clean-ats'); const [jobId,setJobId]=useState(state.jobs[0]?.id||''); const [score,setScore]=useState(null); const [letter,setLetter]=useState(null); return <section className="studio"><div className="card"><h3>Resume editor</h3><div className="triple"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Version name"/><select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{state.templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><select value={jobId} onChange={e=>setJobId(e.target.value)}>{state.jobs.map(j=><option value={j.id} key={j.id}>{j.company} — {j.title}</option>)}</select></div><textarea className="resume" value={resume} onChange={e=>setResume(e.target.value)}/><div className="inline"><button onClick={async()=>{await api('/api/profile',{method:'PUT',body:JSON.stringify({resumeText:resume})});await api('/api/resumes',{method:'POST',body:JSON.stringify({name,templateId,content:resume})});reload()}}><Save size={16}/> Save version</button><button className="secondary" onClick={async()=>setScore(await api('/api/resume/score',{method:'POST',body:JSON.stringify({resumeText:resume,jobId})}))}>Analyze ATS fit</button></div>{score&&<div className="score"><b>{score.score}% ATS alignment</b><p>{score.keywordHits.length} keywords matched · {score.quantifiedBullets} quantified outcomes</p>{score.suggestions.map(s=><p key={s}>• {s}</p>)}</div>}</div><div className="card"><h3>Saved versions</h3>{state.resumes.length?state.resumes.map(r=><button className="version" key={r.id} onClick={()=>setResume(r.content)}><b>{r.name}</b><span>{state.templates.find(t=>t.id===r.templateId)?.name||r.templateId}</span></button>):<p className="empty">Save your first tailored version.</p>}<h3>Cover letter</h3><button onClick={async()=>setLetter(await api('/api/cover-letters',{method:'POST',body:JSON.stringify({jobId})}))}><Sparkles size={16}/> Generate locally</button><textarea className="letter" value={letter?.body||''} onChange={e=>setLetter({...letter,body:e.target.value})} placeholder="Your draft appears here."/></div></section>}
function Agent({state,reload}){ const [q,setQ]=useState(state.profile.targetRoles?.[0]||'product engineer'); const [minFit,setMinFit]=useState(60); return <section className="grid"><div className="card hero"><h2>Local autonomous hunt</h2><p>Profile → local sources → scoring → deduplication → saved matches. Every action is visible and reproducible.</p><input value={q} onChange={e=>setQ(e.target.value)}/><label>Minimum fit: <b>{minFit}%</b><input type="range" min="30" max="95" value={minFit} onChange={e=>setMinFit(Number(e.target.value))}/></label><button onClick={async()=>{await api('/api/agent-runs/start',{method:'POST',body:JSON.stringify({q,minFit})});reload()}}><Bot size={16}/> Start run</button></div><div className="card wide"><h3>Run history</h3>{state.agentRuns.length?state.agentRuns.map(r=><div className="run" key={r.id}><b><CheckCircle2 size={16}/> {r.status} · {r.found} matches</b><small>{r.search?.q} · threshold {r.minFit||60}%</small>{(r.steps||[]).map(s=><p className="step" key={s.name}>✓ <b>{s.name}</b><small>{s.detail}</small></p>)}{r.actions.map(a=><p key={a}>{a}</p>)}</div>):<p className="empty">No runs yet.</p>}</div></section>}
function SettingsPage({state,reload}){ const p=state.profile; const [form,setForm]=useState({...p,skills:(p.skills||[]).join(', '),targetRoles:(p.targetRoles||[]).join(', '),locations:(p.preferences?.locations||[]).join(', '),remote:p.preferences?.remote,minSalary:p.preferences?.minSalary}); const save=async()=>{await api('/api/profile',{method:'PUT',body:JSON.stringify({name:form.name,headline:form.headline,location:form.location,skills:form.skills.split(',').map(x=>x.trim()).filter(Boolean),targetRoles:form.targetRoles.split(',').map(x=>x.trim()).filter(Boolean),preferences:{remote:form.remote,minSalary:Number(form.minSalary)||0,locations:form.locations.split(',').map(x=>x.trim()).filter(Boolean)}})});reload()}; return <section className="split"><div className="card"><h3>Your local profile</h3>{[['name','Name'],['headline','Headline'],['location','Home location'],['targetRoles','Target roles'],['skills','Skills']].map(([key,label])=><label key={key}>{label}<input value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="card"><h3>Search preferences</h3><label>Preferred locations<input value={form.locations||''} onChange={e=>setForm({...form,locations:e.target.value})}/></label><label>Minimum salary<input type="number" value={form.minSalary||0} onChange={e=>setForm({...form,minSalary:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.remote} onChange={e=>setForm({...form,remote:e.target.checked})}/> Include remote roles</label><button onClick={save}><Save size={16}/> Save preferences</button><p className="hint">Used for local fit scores and hunt defaults. Nothing is sent over the network.</p></div></section>}
function Privacy(){ const [file,setFile]=useState(null); const restore=async()=>{if(!file)return;await api('/api/import',{method:'POST',body:await file.text()});location.reload()}; return <section className="grid"><div className="card"><h3><ShieldCheck/> Local-first guarantees</h3><p>All personal data persists to <code>./data/jobhuntr.json</code>. There is no hosted database, telemetry, auth vendor, or required API key.</p></div><div className="card"><h3><Download/> Backup</h3><p>Exports can contain private resume and note data.</p><a className="button" href="/api/export">Download JSON</a> <a className="button secondary" href="/api/export/jobs.csv">Download CSV</a></div><div className="card"><h3><Upload/> Restore</h3><input type="file" accept=".json,application/json" onChange={e=>setFile(e.target.files?.[0])}/><button disabled={!file} onClick={restore}>Restore JSON</button></div><div className="card"><h3>Secret scanning</h3><p><code>npm run secret:scan</code> blocks common private keys, tokens, and copied env files in CI.</p></div></section>}

createRoot(document.getElementById('root')).render(<App />);
